### ISSUE TITLE
Vagrantfile needs build out

### ISSUE THREAD

**Issue by jerrywardlow** [jerrywardlow/eclipse#2]
Vagrantfile needs to be filled out to match README spec

https://github.com/jerrywardlow/eclipse/tree/vagrant/init

**Comment by yevgenybulochnik** [comment]
I will get something started for an initial vagrant file. It will likely be something similar to what I did for dreadnought but with provisioning left out.

**Comment by yevgenybulochnik** [comment]
Initial vagrant file built

**Comment by jerrywardlow** [comment]
Fixed in #4
